# Generated by Django 5.1.2 on 2024-10-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloraclecostcodes",
            name="code",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="historicaloraclecostcodes",
            name="description",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="oraclecostcodes",
            name="code",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="oraclecostcodes",
            name="description",
            field=models.CharField(null=True),
        ),
    ]
