# Generated by Django 5.1.2 on 2024-11-12 15:34

from django.db import migrations, models

import profiles.models.base_models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstaffssoprofile",
            name="other_emails",
            field=profiles.models.base_models.AuthoritativeArrayField(
                base_field=models.EmailField(max_length=254, unique=True),
                blank=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="staffssoprofile",
            name="other_emails",
            field=profiles.models.base_models.AuthoritativeArrayField(
                base_field=models.EmailField(max_length=254, unique=True),
                blank=True,
                size=None,
            ),
        ),
    ]
