# Generated by Django 5.1.4 on 2025-01-02 13:10

from django.db import migrations, models


def forward(apps, schema_editor):
    StaffSSOProfileEmail = apps.get_model("profiles", "StaffSSOProfileEmail")
    records_to_update = StaffSSOProfileEmail.objects.filter(type="work")
    records_to_update.update(type="verified")


def backward(apps, scheme_editor):
    StaffSSOProfileEmail = apps.get_model("profiles", "StaffSSOProfileEmail")
    records_to_update = StaffSSOProfileEmail.objects.filter(type="verified")
    records_to_update.update(type="work")


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_historicalprofile_is_active_profile_is_active"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="staffssoprofileemail",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="historicalstaffssoprofileemail",
            name="type",
            field=models.CharField(
                choices=[
                    ("VERIFIED", "verified"),
                    ("CONTACT", "contact"),
                    ("USER_ADDED", "user-added"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="staffssoprofileemail",
            name="type",
            field=models.CharField(
                choices=[
                    ("VERIFIED", "verified"),
                    ("CONTACT", "contact"),
                    ("USER_ADDED", "user-added"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="staffssoprofileemail",
            unique_together={("profile", "email", "type", "preferred")},
        ),
        migrations.RunPython(forward, backward),
    ]
