# Generated by Django 5.1.5 on 2025-01-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0004_rename_preferred_email_historicalprofile_primary_email_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "reference_id",
                    models.CharField(
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Reference ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("country", "Country"), ("territory", "Territory")],
                        max_length=9,
                    ),
                ),
                (
                    "iso_1_code",
                    models.CharField(
                        max_length=3, unique=True, verbose_name="ISO 1 Code"
                    ),
                ),
                (
                    "iso_2_code",
                    models.CharField(
                        max_length=2, unique=True, verbose_name="ISO 2 Code"
                    ),
                ),
                (
                    "iso_3_code",
                    models.CharField(
                        max_length=3, unique=True, verbose_name="ISO 3 Code"
                    ),
                ),
                ("overseas_region", models.CharField(max_length=40, null=True)),
                ("start_date", models.DateField(null=True)),
                ("end_date", models.DateField(null=True)),
            ],
        ),
    ]
