# Generated by Django 5.1.5 on 2025-02-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_country_historicalpeoplefinderteam_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="country",
            old_name="is_active",
            new_name="is_not_deleted_upstream",
        ),
        migrations.RenameField(
            model_name="ukstafflocation",
            old_name="is_active",
            new_name="is_not_deleted_upstream",
        ),
    ]
