# Generated by Django 5.1.5 on 2025-01-24 10:47

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_alter_country_options_grade_keyskill_profession_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=130, unique=True)),
                (
                    "name",
                    models.CharField(
                        help_text="The full name of this team (e.g. Digital, Data and Technology)",
                        max_length=255,
                        verbose_name="Team name (required)",
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        blank=True,
                        help_text="A short form of the team name, up to 10 characters. For example DDaT.",
                        max_length=20,
                        null=True,
                        verbose_name="Team acronym or initials",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Find out who is in the team and their contact details.\n\nYou can update this description, by [updating your team information](https://workspace.trade.gov.uk/working-at-dbt/how-do-i/update-my-team-information-on-people-finder/).\n",
                        help_text="What does this team do? Use Markdown to add lists and links. Enter up to 1500 characters.",
                        verbose_name="Team description",
                    ),
                ),
                (
                    "leaders_ordering",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("alphabetical", "Alphabetical"),
                            ("custom", "Custom"),
                        ],
                        default="alphabetical",
                        max_length=12,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalTeam",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(max_length=130)),
                (
                    "name",
                    models.CharField(
                        help_text="The full name of this team (e.g. Digital, Data and Technology)",
                        max_length=255,
                        verbose_name="Team name (required)",
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        blank=True,
                        help_text="A short form of the team name, up to 10 characters. For example DDaT.",
                        max_length=20,
                        null=True,
                        verbose_name="Team acronym or initials",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Find out who is in the team and their contact details.\n\nYou can update this description, by [updating your team information](https://workspace.trade.gov.uk/working-at-dbt/how-do-i/update-my-team-information-on-people-finder/).\n",
                        help_text="What does this team do? Use Markdown to add lists and links. Enter up to 1500 characters.",
                        verbose_name="Team description",
                    ),
                ),
                (
                    "leaders_ordering",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("alphabetical", "Alphabetical"),
                            ("custom", "Custom"),
                        ],
                        default="alphabetical",
                        max_length=12,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical team",
                "verbose_name_plural": "historical teams",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
