# Generated by Django 5.1.5 on 2025-01-24 17:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_peoplefinder_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(fields=["code"], name="profiles_gr_code_e4674a_idx"),
        ),
        migrations.AddIndex(
            model_name="keyskill",
            index=models.Index(fields=["code"], name="profiles_ke_code_b77c9f_idx"),
        ),
        migrations.AddIndex(
            model_name="peoplefinderprofile",
            index=models.Index(fields=["slug"], name="profiles_pe_slug_2944f1_idx"),
        ),
        migrations.AddIndex(
            model_name="profession",
            index=models.Index(fields=["code"], name="profiles_pr_code_0519a3_idx"),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["sso_email_id"], name="profiles_pr_sso_ema_8a3590_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(fields=["slug"], name="profiles_te_slug_6e4ca0_idx"),
        ),
        migrations.AddIndex(
            model_name="ukstafflocation",
            index=models.Index(fields=["code"], name="profiles_uk_code_56d730_idx"),
        ),
        migrations.AddIndex(
            model_name="workday",
            index=models.Index(fields=["code"], name="profiles_wo_code_69b9d7_idx"),
        ),
    ]
