# Generated by Django 5.1.5 on 2025-02-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0007_alter_historicalpeoplefinderprofile_additional_roles_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpeoplefinderprofile",
            name="edited_or_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalpeoplefinderprofile",
            name="first_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="historicalpeoplefinderprofile",
            name="last_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="peoplefinderprofile",
            name="edited_or_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="peoplefinderprofile",
            name="first_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="peoplefinderprofile",
            name="last_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
