# Generated by Django 5.1.5 on 2025-01-24 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_grade_profiles_gr_code_e4674a_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="peoplefinderprofile",
            options={},
        ),
    ]
