# Generated by Django 5.1.5 on 2025-02-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0008_alter_historicalpeoplefinderprofile_edited_or_confirmed_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="overseas_region",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
