# Generated by Django 5.1.5 on 2025-03-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0009_alter_country_end_date_alter_country_overseas_region_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpeoplefinderteam",
            name="team_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("standard", "Standard"),
                    ("directorate", "Directorate"),
                    ("portfolio", "Portfolio"),
                ],
                default="standard",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="peoplefinderteam",
            name="team_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("standard", "Standard"),
                    ("directorate", "Directorate"),
                    ("portfolio", "Portfolio"),
                ],
                default="standard",
                max_length=20,
            ),
        ),
    ]
