# Generated by Django 5.1.5 on 2025-03-21 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0011_alter_historicalpeoplefinderprofile_additional_roles_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="country",
            old_name="is_not_deleted_upstream",
            new_name="exists_in_last_import",
        ),
        migrations.RenameField(
            model_name="ukstafflocation",
            old_name="is_not_deleted_upstream",
            new_name="exists_in_last_import",
        ),
    ]
