# Generated by Django 5.1.5 on 2025-03-21 14:43

from django.db import connection, migrations


class Migration(migrations.Migration):

    def fix_ingest_tables():
        migrations_to_action = []
        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT column_name FROM information_schema.columns WHERE table_name = 'profiles_country';"
            )
            country_table_struct = cursor.fetchall()
            cursor.execute(
                "SELECT column_name FROM information_schema.columns WHERE table_name = 'profiles_ukstafflocation';"
            )
            uk_staff_locations_struct = cursor.fetchall()

            if ("is_not_deleted_upstream",) in country_table_struct:
                migrations_to_action.append(
                    migrations.RenameField(
                        model_name="country",
                        old_name="is_not_deleted_upstream",
                        new_name="exists_in_last_import",
                    )
                )
            if ("is_not_deleted_upstream",) in uk_staff_locations_struct:
                migrations_to_action.append(
                    migrations.RenameField(
                        model_name="ukstafflocation",
                        old_name="is_not_deleted_upstream",
                        new_name="exists_in_last_import",
                    )
                )
        return migrations_to_action

    dependencies = [
        (
            "profiles",
            "0011_alter_historicalpeoplefinderprofile_additional_roles_and_more",
        ),
    ]

    # Dynamic list of Migration Actions returned based on the existance of is_not_deleted_upstream
    operations = [*fix_ingest_tables()]
