# Generated by Django 5.1.5 on 2025-04-01 09:52

from django.db import migrations


def add_root_team(apps, schema_editor):
    PeopleFinderTeam = apps.get_model("profiles", "PeopleFinderTeam")
    PeopleFinderTeamTree = apps.get_model("profiles", "PeopleFinderTeamTree")

    root_team, _ = PeopleFinderTeam.objects.get_or_create(
        slug="root-team",
        name="Root team",
        abbreviation="RT",
    )

    PeopleFinderTeamTree.objects.get_or_create(
        parent=root_team, child=root_team, depth=0
    )


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0012_fix_ingest_tables"),
    ]

    operations = [
        migrations.RunPython(add_root_team),
    ]
