# Generated by Django 5.1.8 on 2025-05-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0013_add_root_team_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectorList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("exists_in_last_import", models.BooleanField(default=True)),
                ("sector_id", models.CharField(max_length=255, unique=True)),
                ("full_sector_name", models.CharField(max_length=255)),
                (
                    "sector_cluster_name_april_2023_onwards",
                    models.CharField(max_length=255),
                ),
                (
                    "sector_cluster_name_before_april_2023",
                    models.CharField(max_length=255),
                ),
                ("sector_name", models.CharField(max_length=255)),
                (
                    "sub_sector_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sub_sub_sector_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
