services:
  web:
    env_file: ".env"
    build:
      context: .
      dockerfile: "docker/Dockerfile"
      cache_from:
        - identity/main:latest
    image: identity/main:latest
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.developer
      - INFRA_SERVICE=MAIN
      - DD_TRACE_ENABLED=False
      - DD_INSTRUMENTATION_TELEMETRY_ENABLED=False
    stdin_open: true
    tty: true

  postgres:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7.4.0
    ports:
      - "6379:6379"

  peoplefinder:
    image: identity/main:latest
    command: python manage.py runserver 0.0.0.0:8000
    profiles:
      - services
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.developer
      - INFRA_SERVICE=PEOPLEFINDER
      - DD_TRACE_ENABLED=False
      - DD_INSTRUMENTATION_TELEMETRY_ENABLED=False

  api-scim:
    image: identity/main:latest
    command: python manage.py runserver 0.0.0.0:8000
    profiles:
      - services
    ports:
      - "8002:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.developer
      - INFRA_SERVICE=SSO_SCIM
      - DD_TRACE_ENABLED=False
      - DD_INSTRUMENTATION_TELEMETRY_ENABLED=False

  api-sso-profile:
    image: identity/main:latest
    command: python manage.py runserver 0.0.0.0:8000
    profiles:
      - services
    ports:
      - "8003:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.developer
      - INFRA_SERVICE=SSO_PROFILE
      - DD_TRACE_ENABLED=False
      - DD_INSTRUMENTATION_TELEMETRY_ENABLED=False
