services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7.4.0
    ports:
      - "6379:6379"

  web:
    env_file: ".env"
    build:
      context: .
      dockerfile: "docker/Dockerfile"
      cache_from:
        - identity/main:latest
    image: identity/main:latest
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
      - localstack
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.developer
      - INFRA_SERVICE=MAIN
      - DD_TRACE_ENABLED=False
      - DD_INSTRUMENTATION_TELEMETRY_ENABLED=False
    stdin_open: true
    tty: true

  api-peoplefinder:
    image: identity/main:latest
    command: python manage.py runserver 0.0.0.0:8000
    profiles:
      - services
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.developer
      - INFRA_SERVICE=PEOPLEFINDER
      - DD_TRACE_ENABLED=False
      - DD_INSTRUMENTATION_TELEMETRY_ENABLED=False

  api-scim:
    image: identity/main:latest
    command: python manage.py runserver 0.0.0.0:8000
    profiles:
      - services
    ports:
      - "8002:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.developer
      - INFRA_SERVICE=SSO_SCIM
      - DD_TRACE_ENABLED=False
      - DD_INSTRUMENTATION_TELEMETRY_ENABLED=False

  api-sso-profile:
    image: identity/main:latest
    command: python manage.py runserver 0.0.0.0:8000
    profiles:
      - services
    ports:
      - "8003:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.developer
      - INFRA_SERVICE=SSO_PROFILE
      - DD_TRACE_ENABLED=False
      - DD_INSTRUMENTATION_TELEMETRY_ENABLED=False

  celery-worker:
    image: identity/main:latest
    command: celery -A config.celery worker -l INFO
    profiles:
      - services
    volumes:
      - .:/app 
    depends_on:
      - postgres
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.developer
      - INFRA_SERVICE=CELERY
      - DD_TRACE_ENABLED=False
      - DD_INSTRUMENTATION_TELEMETRY_ENABLED=False

  celery-beat:
    image: identity/main:latest
    command: celery -A config.celery beat -l INFO
    profiles:
      - services
    volumes:
      - .:/app 
    depends_on:
      - postgres
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.developer
      - INFRA_SERVICE=CELERY
      - DD_TRACE_ENABLED=False
      - DD_INSTRUMENTATION_TELEMETRY_ENABLED=False


  localstack:
    build:
      context: ./docker
      dockerfile: Dockerfile.localstack
    ports:
      - '4563-4599:4563-4599'
    environment:
      - DISABLE_CORS_CHECKS=1
      - DISABLE_CUSTOM_CORS_S3=1
      - AWS_DEFAULT_REGION=eu-west-2
      - EDGE_PORT=4566
      - SERVICES=s3,sts,iam
    volumes:
      - "./.localstack/mounted:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
