services:
  web:
    env_file: ".env"
    build:
      context: .
      dockerfile: "docker/Dockerfile"
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.developer
    stdin_open: true
    tty: true

  postgres:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7.4.0
    ports:
      - "6379:6379"