PROFILE_TYPE_STAFF_SSO = "SSO"
PROFILE_TYPE_PEOPLEFINDER = "PF"
PROFILE_TYPE_ORACLE = "ORACLE"

PROFILE_TYPES = (
    (PROFILE_TYPE_STAFF_SSO, "Staff SSO"),
    (PROFILE_TYPE_PEOPLEFINDER, "People Finder"),
    (PROFILE_TYPE_ORACLE, "Oracle"),
)
