# Generated by Django 5.1.4 on 2024-12-31 13:30

from django.db import migrations


def forward(apps, schema_editor):
    """For the purposes of Audit Logs that don't have specific users"""
    User = apps.get_model("user", "User")
    User.objects.create(sso_email_id="via-api")


def backward(apps, schema_editor):
    User = apps.get_model("user", "User")
    User.objects.get(sso_email_id="via-api").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_managers_remove_user_date_joined_and_more"),
    ]

    operations = [  #  type: ignore
        migrations.RunPython(forward, backward),
    ]
