# Generated by Django 5.1.5 on 2025-01-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("user", "0003_auto_20241231_1330"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["sso_email_id"], name="user_user_sso_ema_bb9ca1_idx"
            ),
        ),
    ]
