# Generated by Django 5.1.5 on 2025-01-30 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_user_user_user_sso_ema_bb9ca1_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="user_user_sso_ema_bb9ca1_idx",
        ),
    ]
