name: Identity CI

on:
  pull_request: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Create a .env file
        run: cp .env.ci .env

      - name: Install poetry
        run: pip install poetry

      - name: Install python dependencies
        run: poetry install

      - name: Install node packages
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Run check-black
        run: make check-black

      - name: Run check-isort
        run: make check-isort
      
      - name: Run check-mypy
        run: make check-mypy

      - name: Docker compose up
        run: docker compose up -d

      - name: Run check migrations
        run: make check-migrations

      - name: Run check django
        run: make check-django

      - name: Run tests
        run: make coverage

      - name: Docker compose down
        run: docker compose down