name: Build and test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Create a .env file
        run: cp .env.ci .env

      - name: Build container
        run: make build

      - name: Run checks
        run: make check

      - name: Run check django
        run: make check-django

      - name: Run tests
        run: make coverage

      - name: Docker compose down
        run: docker compose down
